
tls:
  certificates:
    - certFile: /etc/traefik/tls.crt
      keyFile: /etc/traefik/tls.key
      stores:
        - default
  options:
    mtls:
      sniStrict: false
      clientAuth:
        clientAuthType: RequestClientCert
        caFiles:
          - /etc/traefik/ca.crt
  stores:
    default:
      defaultCertificate:
        certFile: /cert/tls.crt
        keyFile: /cert/tls.key
