#http:
#  routers:
#    whoami-router:
#      entryPoints:
#        - web
##        - websecure
#      service: whoami
##      tls: {}
#      rule: Host(`whoami.file.localhost`)
#      middlewares:
#        - mtls-file
#  services:
#    whoami:
#      loadBalancer:
#        servers:
#          - url: http://whoami:8082/
#        passHostHeader: false
#  middlewares:
#    mtls-file:
#      plugin:
#        mTlsRedirect:
#          message: "configMessage"

tls:
  certificates:
    - certFile: /etc/traefik/tls.crt
      keyFile: /etc/traefik/tls.key
      stores:
        - default
  options:
    mtls:
      sniStrict: false
      clientAuth:
        clientAuthType: RequestClientCert
        caFiles:
          - /etc/traefik/ca.crt
  stores:
    default:
      defaultCertificate:
        certFile: /cert/tls.crt
        keyFile: /cert/tls.key
